export interface Adoption {
  adminApprove: string,
  adoptCount: number,
  adoptionId: string,
  time: number,
  date: string,
  petAge: number,
  petBreed: string,
  petCategory: string,
  petCondition: string,
  petDescription: string,
  petGender: string,
  petImage: string,
  petMedicalRecord: string,
  petName: string,
  petSpayStatus: string,
  userId: string,
  userImage: string,
  userName: string,
}
